server:
  port: 8080

mybatis:
  mapper-locations:
    - mapper/*.xml
    - dao/*.xml
# 应用名称
spring:
  application:
    name: admin-mall
  datasource:
    url: jdbc:mysql://localhost:3306/mall?nullCatalogMeansCurrent=true&useUnicode=true&characterEncodeing=utf-8&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ahui940722


