server:
  port: 9001

spring:
  application:
    name: gateway-mall
  cloud:
    gateway:
      enabled: true # 启用网关
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: oauth2-mall # 路由id
          uri: lb://oauth2-mall # 配置路劲
          predicates: # 谓词
            - Path=/oauth2-mall/**
